version: '3.8'

services:
  # Base de datos MySQL para métricas
  mysql-metrics:
    image: mysql:8.0
    container_name: ojoahi-mysql-metrics
    environment:
      MYSQL_ROOT_PASSWORD: grafana123
      MYSQL_DATABASE: metrics
      MYSQL_USER: grafana
      MYSQL_PASSWORD: grafana123
    ports:
      - "3307:3306"
    volumes:
      - mysql-metrics-data:/var/lib/mysql
    networks:
      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: ojoahi-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - mysql-metrics
    networks:
      - monitoring

  # Prometheus para métricas (configuración simplificada)
  prometheus:
    image: prom/prometheus:latest
    container_name: ojoahi-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - monitoring

  # Node Exporter para métricas del sistema
  node-exporter:
    image: prom/node-exporter:latest
    container_name: ojoahi-node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    networks:
      - monitoring

volumes:
  grafana-storage:
  mysql-metrics-data:
  prometheus-data:

networks:
  monitoring:
    driver: bridge
